"""Add email to user table

Revision ID: c2a9d435539f
Revises: 01d911661aec
Create Date: 2024-09-03 14:42:51.992603

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.

revision = 'c2a9d435539f'
down_revision = '01d911661aec'
branch_labels = None
depends_on = None


def upgrade():

    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.alter_column('password',
                existing_type=mysql.VARCHAR(length=200),
                type_=sa.String(length=128),
                existing_nullable=False)
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():

    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password',
                existing_type=sa.String(length=128),
                type_=mysql.VARCHAR(length=200),
                existing_nullable=False)
        batch_op.drop_column('email')

